version: '3.4'

services:
   metric.api:
    image: metric.api
    build:
     context: .
     dockerfile: ./Dockerfile
   prometheus:
    image: prom/prometheus:v2.37.9
    volumes: 
       - ./prometheus.yml:/etc/prometheus/prometheus.yml
   jaeger:
    image: jaegertracing/all-in-one:1.49  
   elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.1  
   kibana:
    image: docker.elastic.co/kibana/kibana:8.8.1  
   grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "5200:3000"
    volumes:
      - ./grafana-data/data:/var/lib/grafana
 
      
